development:
   adapter: mysql2
   database: FS_dev
   username: root
   password: root
   host: localhost
   socket: /Applications/MAMP/tmp/mysql/mysql.sock

test:
   adapter: mysql2
   database: FS_test
   username: root
   password: root
   host: localhost
   socket: /Applications/MAMP/tmp/mysql/mysql.sock

production:
   adapter: mysql2
   database: FS_prod
   username: root
   password: root
   host: localhost
   socket: /Applications/MAMP/tmp/mysql/mysql.sock
