# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e232dbe28c8828ecfc40395382d31b38aa285a46886794cea5d4a559d9760f61a99e06031fb8f52320eb8f447679018dbe914251e3ec68e9bd3081ab6a2ee1a4

test:
  secret_key_base: acfd6dbc07f888b0458008f1a9204dc894654e42c6c2c610fbeaf74783db5c23008f9e9524b0f9f56f9b39f32c1025c64585a2fd65b4db58d7492a09fae97b06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
